<a href="https://colab.research.google.com/github/HasanALI313/Covnets/blob/main/RecurrentNeuralNetwork(RNN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.datasets import imdb
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

17473536/17464789 [==============================] - 0s 0us/step


In [ ]:
train_data[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

In [ ]:
train_labels[0:2]

array([1, 0])

In [ ]:
import numpy as np

def vectorize_sequences(sequences, dimension=10000):
    #Creates an all-zero matrix
    results = np.zeros((len(sequences), dimension))
    #Set approperiate indices of the tensor result to 1s
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
    return results

#Turn Python lists into NumPy tensors
x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

# print out parts of x_train to see what is in it...
print(x_train[:9])

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [ ]:
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

# print out parts of y_train to see what is in it...
print(y_train[:9])

[1. 0. 0. 1. 0. 0. 1. 0. 1.]


In [ ]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
             metrics=['accuracy'])

In [ ]:
#Setting aside a validation set
x_val = x_train[:10000]
partial_x_train = x_train[10000:]

y_val = y_train[:10000]
partial_y_train = y_train[10000:]

#Training the model
model.fit(partial_x_train,
          partial_y_train,
          epochs=20,
          batch_size=512,
          validation_data=(x_val, y_val))

Epoch 1/20
30/30 [==============================] - 4s 64ms/step - loss: 0.4879 - accuracy: 0.7911 - val_loss: 0.4348 - val_accuracy: 0.8093
Epoch 2/20
30/30 [==============================] - 2s 57ms/step - loss: 0.2892 - accuracy: 0.9025 - val_loss: 0.3133 - val_accuracy: 0.8765
Epoch 3/20
30/30 [==============================] - 2s 60ms/step - loss: 0.2135 - accuracy: 0.9283 - val_loss: 0.2729 - val_accuracy: 0.8909
Epoch 4/20
30/30 [==============================] - 2s 54ms/step - loss: 0.1645 - accuracy: 0.9473 - val_loss: 0.2887 - val_accuracy: 0.8827
Epoch 5/20
30/30 [==============================] - 1s 42ms/step - loss: 0.1353 - accuracy: 0.9541 - val_loss: 0.3009 - val_accuracy: 0.8814
Epoch 6/20
30/30 [==============================] - 1s 37ms/step - loss: 0.1130 - accuracy: 0.9630 - val_loss: 0.3078 - val_accuracy: 0.8807
Epoch 7/20
30/30 [==============================] - 1s 36ms/step - loss: 0.0893 - accuracy: 0.9742 - val_loss: 0.3223 - val_accuracy: 0.8808
Epoch 8/20
30

In [ ]:
#Evaluation
results = model.evaluate(x_test, y_test)

782/782 [==============================] - 2s 3ms/step - loss: 0.7800 - accuracy: 0.8490


In [ ]:
from prettytable import PrettyTable
#Prediction
preds = model.predict(x_test [0:10])

t = PrettyTable(['Real', 'Predicted'])
for i, pred in enumerate(preds):
    t.add_row([y_test [i], round(preds [i,0],2)])
print(t)

+------+-----------+
| Real | Predicted |
+------+-----------+
| 0.0  |    0.01   |
| 1.0  |    1.0    |
| 1.0  |    0.9    |
| 0.0  |    0.98   |
| 1.0  |    1.0    |
| 1.0  |    1.0    |
| 1.0  |    0.98   |
| 0.0  |    0.0    |
| 0.0  |    0.99   |
| 1.0  |    1.0    |
+------+-----------+


In [ ]:
from keras.datasets import imdb
from keras.preprocessing import sequence

max_features = 10000
maxlen = 500
batch_size = 32

#Load data and pad it
(input_train, y_train), (input_test, y_test) = imdb.load_data(num_words=max_features)
input_train = sequence.pad_sequences(input_train, maxlen=maxlen)
input_test = sequence.pad_sequences(input_test, maxlen=maxlen)

In [ ]:
from keras.layers import Embedding, SimpleRNN, Dense

#Define model
model = models.Sequential()
model.add(Embedding(max_features, 32))
model.add(SimpleRNN(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop', 
              loss='binary_crossentropy', 
              metrics=['acc'])

#Train the model
model.fit(input_train, y_train,
          epochs=15,
          batch_size=128,
          validation_split=0.2)

Epoch 1/15
157/157 [==============================] - 29s 171ms/step - loss: 0.5698 - acc: 0.6951 - val_loss: 0.4320 - val_acc: 0.8072
Epoch 2/15
157/157 [==============================] - 29s 185ms/step - loss: 0.3574 - acc: 0.8552 - val_loss: 0.3600 - val_acc: 0.8476
Epoch 3/15
157/157 [==============================] - 27s 170ms/step - loss: 0.2867 - acc: 0.8888 - val_loss: 0.4511 - val_acc: 0.7912
Epoch 4/15
157/157 [==============================] - 27s 174ms/step - loss: 0.2186 - acc: 0.9160 - val_loss: 0.3629 - val_acc: 0.8478
Epoch 5/15
157/157 [==============================] - 26s 167ms/step - loss: 0.1751 - acc: 0.9355 - val_loss: 0.3599 - val_acc: 0.8572
Epoch 6/15
157/157 [==============================] - 27s 172ms/step - loss: 0.1257 - acc: 0.9546 - val_loss: 0.4007 - val_acc: 0.8584
Epoch 7/15
157/157 [==============================] - 26s 168ms/step - loss: 0.0947 - acc: 0.9678 - val_loss: 0.7575 - val_acc: 0.7150
Epoch 8/15
157/157 [==============================] - 2

In [ ]:
#Evaluation
results = model.evaluate(input_test, y_test)

782/782 [==============================] - 21s 27ms/step - loss: 0.8259 - acc: 0.7958


In [ ]:
#Define model
model = models.Sequential()
model.add(Embedding(max_features, 32))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop', 
              loss='binary_crossentropy', 
              metrics=['acc'])

#Train the model
model.fit(input_train, y_train,
          epochs=1,
          batch_size=128,
          validation_split=0.2)


157/157 [==============================] - 103s 623ms/step - loss: 0.6636 - acc: 0.5818 - val_loss: 0.4986 - val_acc: 0.7574


In [ ]:
#Evaluation
results = model.evaluate(input_test, y_test)

782/782 [==============================] - 74s 95ms/step - loss: 0.4929 - acc: 0.7666


In [ ]:
# How to setup a CNN model for imdb sentiment analysis in Keras

def Snippet_381(): 

    print()
    print(format('How to setup a CNN model for sentiment analysis in Keras','*^82'))

    import time
    start_time = time.time()

    # load libraries
    from keras.datasets import imdb
    from keras.models import Sequential
    from keras.layers import Dense, Flatten
    from keras.layers.convolutional import Conv1D, MaxPooling1D
    from keras.layers.embeddings import Embedding
    from keras.preprocessing import sequence
    
    # load data and Set the number of words we want
    top_words = 5000
    input_length = 500

    # Load data and target vector from movie review data
    (X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=top_words)
    
    print(); print(X_train.shape); print(X_train)
    print(); print(y_train.shape); print(y_train)    
    print(); print(X_test.shape);  print(X_test)
    print(); print(y_test.shape);  print(y_test)    
    
    # Convert movie review data to feature matrix
    X_train = sequence.pad_sequences(X_train, maxlen=input_length)
    print(); print(X_train.shape); print(X_train)

    X_test = sequence.pad_sequences(X_test, maxlen=input_length)
    print(); print(X_test.shape);  print(X_test)

    # setup a CNN network
    model = Sequential()
    model.add(Embedding(top_words, 32, input_length=input_length))
    model.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Flatten())
    model.add(Dense(250, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.summary()

    # Fit the model
    model.fit(X_train, y_train, validation_data=(X_test, y_test), 
              epochs=20, batch_size=128, verbose=1)

    # Final evaluation of the model
    scores = model.evaluate(X_test, y_test, verbose=1)

    print("Accuracy: %.2f%%" % (scores[1]*100))
    print(); print("Execution Time %s seconds: " % (time.time() - start_time))

Snippet_381()


*************How to setup a CNN model for sentiment analysis in Keras*************
17473536/17464789 [==============================] - 0s 0us/step

(25000,)
[list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 2, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 2, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 2, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 2, 18, 51, 36, 28, 224, 92, 25, 104, 4, 2